// Auto-generated by scripts/prebake-local.ts. Do not edit by hand.
export type FeaturedSample = {
  label: string;
  url: string;
  vibeId: string;
};

export const FEATURED: FeaturedSample[] = [
  {
    "label": "tokyo coffee shop",
    "url": "local://snaptik_7541363142295637256_v3.mp4",
    "vibeId": "v-moy3gfzt-6cx3"
  }
];
