// Pre-bake ONE demo from a local mp4 file. Bypasses yt-dlp.
// Hero-only video mode (1× 8s Veo clip with native audio, ~60s wall time).
//
// Usage: npx tsx scripts/prebake-local.ts demo/snaptik_*.mp4 "tokyo coffee shop"

// Manual .env.local load — must happen BEFORE any lib imports because
// some lib modules read process.env at module-evaluation time.
import { readFileSync } from "fs";
try {
  const env = readFileSync(".env.local", "utf8");
  let loaded = 0;
  for (const line of env.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    process.env[key] = val;
    loaded++;
  }
  console.log(`env loaded: ${loaded} keys, OPENAI_API_KEY=${process.env.OPENAI_API_KEY ? "set(" + process.env.OPENAI_API_KEY.length + ")" : "MISSING"}`);
} catch (e) {
  console.warn("could not load .env.local:", e);
}

// Force hero-only mode for this prebake.
process.env.VIBER_VIDEO_MODE = "hero-only";

import { promises as fs } from "fs";
import path from "path";
import { extractFromUpload } from "../lib/extract";
import { generateMusicAsset, generateVideoAsset } from "../lib/generate";
import { saveVibe } from "../lib/vibe-store";

async function main() {
  const inputPath = process.argv[2];
  const label = process.argv[3] || "demo sample";
  if (!inputPath) {
    console.error("usage: tsx scripts/prebake-local.ts <video.mp4> [label]");
    process.exit(1);
  }
  const abs = path.resolve(inputPath);
  await fs.access(abs);
  const stat = await fs.stat(abs);
  console.log(`\nViber prebake (local) — ${label}`);
  console.log(`  ${abs} (${Math.round(stat.size / 1024)}kb)`);

  const t0 = Date.now();

  console.log("\n[1/3] extract …");
  const vibe = await extractFromUpload({
    videoPath: abs,
    originalName: path.basename(abs),
    contentType: "video/mp4",
  });
  await saveVibe(vibe);
  console.log(`      vibeId = ${vibe.id}`);
  console.log(`      title  = ${vibe.title}`);
  console.log(`      audio  = ${vibe.audioAnalysis ? `${vibe.audioAnalysis.genre} / ${vibe.audioAnalysis.tempoBpm} bpm` : "(none)"}`);

  console.log("\n[2/3] music …");
  const music = await generateMusicAsset(vibe);
  const next1 = {
    ...vibe,
    generatedAssets: {
      ...(vibe.generatedAssets ?? {}),
      musicUrl: music.url,
      musicPrompt: music.prompt,
      musicDurationMs: music.lengthMs,
    },
  };
  await saveVibe(next1);
  console.log(`      ${music.url} (${Math.round(music.bytes / 1024)}kb)`);

  console.log("\n[3/3] video (hero-only) …");
  const video = await generateVideoAsset(next1, music.localPath);
  const next2 = {
    ...next1,
    generatedAssets: {
      ...(next1.generatedAssets ?? {}),
      previewVideoUrl: video.url,
      videoDurationSeconds: video.durationSeconds,
    },
  };
  await saveVibe(next2);
  console.log(`      ${video.url} (${Math.round(video.bytes / 1024 / 1024)}mb, ${video.durationSeconds}s)`);

  // Write featured.ts so the landing page sample chip points here.
  const featuredFile = path.join(process.cwd(), "lib", "featured.ts");
  const body = `// Auto-generated by scripts/prebake-local.ts. Do not edit by hand.
export type FeaturedSample = {
  label: string;
  url: string;
  vibeId: string;
};

export const FEATURED: FeaturedSample[] = ${JSON.stringify(
    [{ label, url: "local://" + path.basename(abs), vibeId: vibe.id }],
    null,
    2,
  )};
`;
  await fs.writeFile(featuredFile, body);
  console.log(`\nWrote ${featuredFile}`);

  console.log(`\nDone in ${Math.round((Date.now() - t0) / 1000)}s`);
  console.log(`Visit: http://localhost:3000/v/${vibe.id}`);
}

main().catch((e) => {
  console.error("\nprebake failed:", e);
  process.exit(1);
});
