// Pre-bake the three demo sample URLs end-to-end so the landing page's
// sample chips link to fully-rendered vibe pages with no waiting.
//
// What it does for each URL:
//   1. extract        (yt-dlp + ffmpeg + GPT vision + Gemini audio + brief)
//   2. generate music (multi-bridge with audio-aware prompt + SFX layer)
//   3. generate video (chain mode, 4× Veo with first-last frame interpolation)
//
// Total per sample: ~5-7 minutes. Three samples = ~15-20 min wall time.
//
// Usage:
//   npx tsx scripts/prebake-demos.ts
//
// Outputs:
//   - .viber/vibes.json updated with three new vibes
//   - public/uploads/{vibeId}-source-sample.mp3 for each
//   - public/generated/{vibeId}-music.mp3 for each
//   - public/generated/{vibeId}.mp4 for each
//   - lib/featured.ts overwritten with the three vibeIds
//
// Re-running is idempotent against an empty .viber/vibes.json. If you want
// to refresh prebakes, delete .viber/vibes.json first (and the matching
// generated/ files).

// Load .env.local the same way `next dev` does. Without this line,
// process.env.OPENAI_API_KEY (and every other key) is undefined when
// tsx runs the script outside of Next's runtime.
import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd());

import { promises as fs } from "fs";
import path from "path";
import { SAMPLES } from "../lib/samples";
import { extractFromYouTube } from "../lib/extract";
import {
  generateMusicAsset,
  generateVideoAsset,
} from "../lib/generate";
import { saveVibe } from "../lib/vibe-store";

type FeaturedEntry = {
  label: string;
  url: string;
  vibeId: string;
};

async function main() {
  console.log("\nViber prebake — three demo samples\n");
  const featured: FeaturedEntry[] = [];

  for (const sample of SAMPLES) {
    const t0 = Date.now();
    console.log(`\n— ${sample.label}`);
    console.log(`  ${sample.url}`);

    try {
      console.log("  [1/3] extract …");
      const vibe = await extractFromYouTube(sample.url);
      await saveVibe(vibe);
      console.log(`        vibeId = ${vibe.id}`);

      console.log("  [2/3] music …");
      const music = await generateMusicAsset(vibe);
      const next1 = {
        ...vibe,
        generatedAssets: {
          ...(vibe.generatedAssets ?? {}),
          musicUrl: music.url,
          musicPrompt: music.prompt,
          musicDurationMs: music.lengthMs,
        },
      };
      await saveVibe(next1);
      console.log(`        ${music.url} (${Math.round(music.bytes / 1024)}kb)`);

      console.log("  [3/3] video …");
      const video = await generateVideoAsset(next1, music.localPath);
      const next2 = {
        ...next1,
        generatedAssets: {
          ...(next1.generatedAssets ?? {}),
          previewVideoUrl: video.url,
          videoDurationSeconds: video.durationSeconds,
        },
      };
      await saveVibe(next2);
      console.log(
        `        ${video.url} (${Math.round(video.bytes / 1024 / 1024)}mb, ${video.durationSeconds}s)`,
      );

      featured.push({
        label: sample.label,
        url: sample.url,
        vibeId: vibe.id,
      });
      console.log(
        `  done in ${Math.round((Date.now() - t0) / 1000)}s · ${featured.length}/${SAMPLES.length}`,
      );
    } catch (e) {
      console.error(`  FAILED: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  if (featured.length === 0) {
    console.error("\nNo samples succeeded. Not writing lib/featured.ts.");
    process.exit(1);
  }

  const featuredFile = path.join(process.cwd(), "lib", "featured.ts");
  const body = `// Auto-generated by scripts/prebake-demos.ts. Do not edit by hand —
// re-run the script to refresh.
//
// These are pre-rendered demo samples used by the landing page. Sample
// chips link directly to /v/{vibeId}, skipping live extraction.

export type FeaturedSample = {
  label: string;
  url: string;
  vibeId: string;
};

export const FEATURED: FeaturedSample[] = ${JSON.stringify(featured, null, 2)};
`;

  await fs.writeFile(featuredFile, body);
  console.log(
    `\nWrote ${featuredFile}\n${featured.length}/${SAMPLES.length} samples baked.\n`,
  );
}

main().catch((e) => {
  console.error("prebake failed:", e);
  process.exit(1);
});
